name: Job Alert Automation

on:
  schedule:
    - cron: '0 13 * * *'  # runs daily at 9:00 AM EST (modify as needed)
  workflow_dispatch:

jobs:
  job-alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Job Alert Script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: |
          python job_hunter.py
